version: "3.3"

services:
  openeocubes:
    build: .
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    container_name: openeocubes
    ports:
      - "8080:8080"
    restart: always
